name: Django CI

# developに対してプルリクを作成した時に発火
on:
  pull_request:
    branches:
      - develop

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
