# Generated by Django 3.2 on 2021-09-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engawa',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField()),
                ('pc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('front', models.CharField(blank=True, max_length=1023, null=True)),
                ('back', models.CharField(blank=True, max_length=1023, null=True)),
                ('invitation_code', models.CharField(blank=True, max_length=8, null=True)),
                ('engawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homaster.engawa')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(max_length=8)),
                ('gm_flag', models.BooleanField()),
                ('engawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homaster.engawa')),
                ('handout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homaster.handout')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_front', models.BooleanField()),
                ('auth_back', models.BooleanField()),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homaster.handout')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homaster.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['engawa', 'p_code'], name='homaster_pl_engawa__310a31_idx'),
        ),
    ]
