# Generated by Django 3.2 on 2021-09-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gm_flag',
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
