# Generated by Django 3.2 on 2021-09-26 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homaster', '0002_auto_20210925_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='handout',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='homaster.handout'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='player',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engawa',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handout',
            name='engawa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='homaster.engawa'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='p_code',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='engawa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='homaster.engawa'),
        ),
        migrations.AlterField(
            model_name='player',
            name='handout',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='homaster.handout'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_code',
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AddConstraint(
            model_name='auth',
            constraint=models.UniqueConstraint(fields=('player', 'handout'), name='auth_unique'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('engawa', 'p_code'), name='pl_unique'),
        ),
    ]
